### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by MarvinErkes** [csh/minecraft-rebel-plugin#1]
Hello,
i need help to setup this,
can you help me?
If you can please add me on Skype, my name is 'marvinerkes'.
Thanks

**Comment by csh** [comment]
Sorry for the delayed response, I'm afraid I don't use Skype though.

There's a brief summary of how to use this on the [spigot resource page](https://www.spigotmc.org/resources/minecraft-rebel.22443/) which links to the appropriate guides for installing plugins and using JRebel.
